In [2]:
import numpy as np

In [4]:
array1 = np.zeros(10)
array1[4] = 1
array1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
array2 = np.arange(10,49)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [12]:
array3 = np.array([1,2,3])
array3[::-1]

array([3, 2, 1])

In [15]:
array4 = np.arange(0,9).reshape(3,3)
print(array4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
array5 = np.array([1,2,0,0,4,0])
final = []
for i in range(len(array5)):
    if array5[i] != 0:
        final.append(i)
final

[0, 1, 4]

In [21]:
array6 = np.random.random((3,3,3))
array6

array([[[0.60083785, 0.63907019, 0.44358832],
        [0.31956932, 0.93342774, 0.5988847 ],
        [0.16144865, 0.81608874, 0.07225446]],

       [[0.65791169, 0.3261419 , 0.21125072],
        [0.83567377, 0.08093767, 0.07833985],
        [0.56390426, 0.8104252 , 0.73315976]],

       [[0.02419599, 0.07932278, 0.02556527],
        [0.84575899, 0.4869416 , 0.9582719 ],
        [0.19908768, 0.36917882, 0.70070532]]])

In [22]:
array7 = np.random.random((10,10))
array7

array([[0.88842845, 0.62233517, 0.89594517, 0.12181495, 0.37097481,
        0.46256192, 0.94156436, 0.38562814, 0.69143055, 0.42304587],
       [0.52225164, 0.81077445, 0.40386356, 0.96001417, 0.48619991,
        0.99449311, 0.25340803, 0.19997752, 0.688602  , 0.47887159],
       [0.45186908, 0.10458744, 0.17548589, 0.64015202, 0.65652141,
        0.0722119 , 0.99252711, 0.51213314, 0.7072834 , 0.35641572],
       [0.17510078, 0.99596691, 0.75269811, 0.29460293, 0.2715325 ,
        0.26547083, 0.2271617 , 0.11475671, 0.01137219, 0.85463911],
       [0.57715142, 0.04512169, 0.28662179, 0.15322645, 0.22882278,
        0.43725509, 0.56589744, 0.01861464, 0.43323706, 0.29922589],
       [0.92530091, 0.54857917, 0.70527052, 0.1828756 , 0.53838682,
        0.11492789, 0.32001634, 0.1618513 , 0.1260521 , 0.43553153],
       [0.17508646, 0.43750337, 0.89397379, 0.69611519, 0.00329582,
        0.16963868, 0.23356845, 0.75082461, 0.80275911, 0.89095721],
       [0.73922214, 0.04508902, 0.1149274

In [27]:
val1 = np.max(array7)
val

0.9959669069313278

In [26]:
val2 = np.min(array7)
val2

0.0032958162988513395

In [29]:
array8 = np.ones((5,5))
array8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
array8[1:-1,1:-1]=0
array8

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])